apiVersion: apps/v1
kind: Deployment
metadata:
    name: quakes-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: quakes-api
        template:
            metadata:
                labels:
                    app: quakes-api
                annotations:
                    dapr.io/enabled: true
                    dapr.io/id: quakes-api
                    dapr.io/port: 3012
    spec:
        containers:
          - image: cdwmodernclouddev20200111acr.azurecr.io/hackfest/quakes-api:1.0
            imagePullPolicy: Always
            name: quakes-api
            resources:
            requests:
                memory: "64Mi"
                cpu: "100m"
            limits:
                memory: "128Mi"
                cpu: "500m"
            env:
              - name: APPINSIGHTS_INSTRUMENTATIONKEY
                valueFrom:
                secretKeyRef:
                    name: cosmos-db-secret
                    key: appinsights
              - name: DATA_SERVICE_URI
                value: http://data-api.hackfest.svc.cluster.local:3009/
              - name: CACHE_SERVICE_URI
                value: http://cache-api.hackfest.svc.cluster.local:3006/
            ports:
              - containerPort: 3012
                protocol: TCP
        restartPolicy: Always