version: '3'
services:
  modernclouddev:
    image: modernclouddev:latest
    container_name: modernclouddev

    # user: vscode

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ..:/workspace
    - /c/users/chwieder/.azure:/root/.azure
    - /c/users/chwieder/.git:/root/.config/git
    - /c/users/chwieder/.kube:/root/.kube
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 